pipeline {
    agent any

    stages {
        stage('Checkout') {
    steps {
        dir('CA2/Part1/gradle-basic-demo') {
            git url: 'https://github.com/fba-araujo/devops-23-24-PSM-1231826.git'
        }
                }
            }
        }
        stage('Assemble') {
            steps {
                dir('CA2/Part1/gradle-basic-demo') {
                    sh 'chmod +x gradlew'
                    sh './gradlew assemble'
                }
            }
        }
        stage('Test') {
            steps {
                dir('CA2/Part1/gradle-basic-demo') {
                    sh './gradlew test'
                    junit 'build/test-results/test/*.xml'
                }
            }
        }
        stage('Archive') {
            steps {
                dir('CA2/Part1/gradle-basic-demo') {
                    archiveArtifacts artifacts: 'build/libs/*.jar', fingerprint: true
                }
            }
        }
    }
}
