pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                dir('CA2/Part2/tutorial-spring-boot-application') {
                    git branch: 'main', url: 'https://github.com/fba-araujo/devops-23-24-PSM-1231826.git'
                }
            }
        }
        stage('Assemble') {
            steps {
                dir('CA2/Part2/tutorial-spring-boot-application') {
                    sh './gradlew assemble'
                }
            }
        }
        stage('Test') {
            steps {
                dir('CA2/Part2/tutorial-spring-boot-application') {
                    sh './gradlew test'
                    junit 'build/test-results/test/*.xml'
                }
            }
        }
        stage('Javadoc') {
            steps {
                dir('CA2/Part2/tutorial-spring-boot-application') {
                    sh './gradlew javadoc'
                    publishHTML(target: [
                        allowMissing: false,
                        alwaysLinkToLastBuild: false,
                        keepAll: true,
                        reportDir: 'build/docs/javadoc',
                        reportFiles: 'index.html',
                        reportName: 'Javadoc'
                    ])
                }
            }
        }
        stage('Archive') {
            steps {
                dir('CA2/Part2/tutorial-spring-boot-application') {
                    archiveArtifacts artifacts: 'build/libs/*.war', fingerprint: true
                }
            }
        }
        stage('Publish Image') {
            steps {
                script {
                    dir('CA2/Part2/tutorial-spring-boot-application') {
                        withCredentials([usernamePassword(credentialsId: 'docker-hub-credentials', usernameVariable: 'DOCKER_HUB_USER', passwordVariable: 'DOCKER_HUB_PASS')]) {
                            def customImage = docker.build("filipaba/devops:ca5")
                            docker.withRegistry('https://index.docker.io/v1/', 'docker-hub-credentials') {
                                customImage.push()
                }
            }
        }
    }
}
