/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package basic_demo;

import org.junit.Test;

import static org.junit.Assert.*;

/**
 * This is a test class for the {@link App} class.
 */
public class AppTest {
    /**
     * Test to verify that the {@link App} class has a greeting.
     */
    @Test
    public void testAppHasAGreeting() {
        App classUnderTest = new App();

        String greeting = classUnderTest.getGreeting();

        assertNotNull("App should have a greeting", greeting);
    }
}